# Iterative Bayesian Unfolding

IBU reconstructs the target distribution by iteratively applying Bayes' rule to the conditional probabilities contained in the detector response matrix.

For a quick start, we deconvolve the distribution of Iris plant types in the famous IRIS data set.

In [1]:
# load the example data
using MLDataUtils
X, y_labels, _ = load_iris()

# discretize the target quantity (for numerical values, we'd use LinearDiscretizer)
using Discretizers: encode, CategoricalDiscretizer
y = encode(CategoricalDiscretizer(y_labels), y_labels) # vector of target value indices
;

In [2]:
# Split the data into training and observed data sets.
# 
# The matrices MLDataUtils expects are transposed, by default.
# Thus, we have to be explicit about obsdim = 1. Note that
# CherenkovDeconvolution.jl follows the convention of ScikitLearn.jl
# (and others), which is size(X_train) == (n_examples, n_features).
# 
# MLDataUtils unfortunately assumes size(X_train) == (n_features, n_examples),
# but obsdim = 1 fixes this assumption.
# 
srand(42) # make split reproducible
(X_train, y_train), (X_data, y_data) = splitobs(shuffleobs((X', y), obsdim = 1), obsdim = 1);

In [3]:
#
# IBU is only applicable with a single discrete observable dimension. In order to obtain 
# a dimension that contains as much information as possible, we discretize the feature
# space with a decision tree, using its leaves as clusters. The cluster indices are the
# discrete values of the observed dimension. This concepts relates to supervised clustering.
#
using ScikitLearn, CherenkovDeconvolution.Sklearn

td = TreeDiscretizer(X_train, y_train, 6) # obtain (up to) 6 clusters
x_train = encode(td, X_train)
x_data  = encode(td, X_data)

# have a look at the content of x_train
unique(x_train) # its the cluster indices

INFO: Utilities of ScikitLearn.jl are available in CherenkovDeconvolution.Sklearn


6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [4]:
#
# Now let's estimate the target distribution!
#
using CherenkovDeconvolution

f_est = ibu(x_data, x_train, y_train) # returns a vector of target value probabilities

3-element Array{Float64,1}:
 0.333333
 0.346387
 0.320279

In [5]:
#
# Compare the result to the true target distribution, which we are estimating
#
f_true = Util.fit_pdf(y_data) # f_est is almost equal to f_true!

3-element Array{Float64,1}:
 0.333333
 0.355556
 0.311111

In [6]:
?ibu # You can find more information in the documentation

search: ibu IOBuffer @inbounds PipeBuffer Distributed is_bsd



```
ibu(data, train, y, x; kwargs...)
```

Iterative Bayesian Unfolding of the target distribution in the DataFrame `data`. The deconvolution is inferred from the DataFrame `train`, where the target column `y` and the observable column `x` are given.

This function wraps `ibu(R, g; kwargs...)`, constructing `R` and `g` from the examples in the two DataFrames.

```
ibu(x_data, x_train, y_train; kwargs...)
```

Iterative Bayesian Unfolding of the target distribution, given the observations in the one-dimensional array `x_data`. The deconvolution is inferred from `x_train` and `y_train`.

This function wraps `ibu(R, g; kwargs...)`, constructing `R` and `g` from the examples in the three arrays.

```
ibu(R, g; kwargs...)
```

Iterative Bayesian Unfolding with the detector response matrix `R` and the observable density function `g`.

### Keyword arguments

  * `f_0 = ones(m) ./ m` defines the prior, which is uniform by default.
  * `smoothing = Base.identity` is a function that optionally applies smoothing in between iterations. The operation is neither applied to the initial prior, nor to the final result. The function `inspect` is called before the smoothing is performed.
  * `K = 3` is the maximum number of iterations.
  * `epsilon = 0.0` is the minimum symmetric Chi Square distance between iterations. If the actual distance is below this threshold, convergence is assumed and the algorithm stops.
  * `inspect = nothing` is a function `(k::Int, chi2s::Float64, f_k::Array) -> Any` optionally called in every iteration.
  * `loggingstream = DevNull` is an optional `IO` stream to write log messages to.
